// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrsjmbzmvngzhdaofhsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyc2ptYnptdm5nemhkYW9maHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTgzNzYsImV4cCI6MjA2NzY3NDM3Nn0.hzHI72U_2nw9Rs1Moyfmub6-i5A77XCHxjoDfUG7-jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});